export const studyCollections = [
  {
    id: 'mus-rotator-cuff',
    title: 'Rotator Cuff Basics',
    description: 'Core cuff actions, stabilization, and common cue language.',
    types: ['mcq', 'reverse'],
    blueprint_codes: ['2.D'],
    tags: ['rotator-cuff', 'shoulder', 'stabilization'],
    query: 'rotator cuff shoulder stabilization',
  },
  {
    id: 'mus-hip-external-rotators',
    title: 'Hip External Rotators',
    description: 'Deep lateral hip rotators and movement context.',
    types: ['mcq', 'reverse'],
    blueprint_codes: ['2.D'],
    tags: ['hip', 'external-rotation'],
    query: 'hip external rotator piriformis',
  },
  {
    id: 'mus-knee-stabilizers',
    title: 'Knee Stabilizers',
    description: 'Knee support muscles and movement roles.',
    types: ['mcq', 'reverse'],
    blueprint_codes: ['2.D'],
    tags: ['knee', 'stability'],
    query: 'knee stabilizer',
  },
  {
    id: 'mus-ankle-pf-df',
    title: 'Plantarflexors vs Dorsiflexors',
    description: 'Ankle action basics for gait and training context.',
    types: ['mcq', 'fill'],
    blueprint_codes: ['2.D'],
    tags: ['ankle', 'plantarflexion', 'dorsiflexion'],
    query: 'plantarflexion dorsiflexion ankle',
  },
  {
    id: 'mus-posture-patterns',
    title: 'Posture Pattern Basics',
    description: 'Upper/lower crossed pattern fundamentals and terminology.',
    types: ['mcq', 'reverse'],
    blueprint_codes: ['2.D'],
    tags: ['posture', 'upper-crossed', 'lower-crossed'],
    query: 'upper crossed lower crossed posture',
  },
  {
    id: 'neuro-ans-basics',
    title: 'ANS Basics',
    description: 'Sympathetic vs parasympathetic essentials.',
    types: ['mcq', 'reverse', 'fill'],
    blueprint_codes: ['1.B.7'],
    tags: ['autonomic', 'sympathetic', 'parasympathetic'],
    query: 'autonomic sympathetic parasympathetic',
  },
  {
    id: 'neuro-reflex-arc',
    title: 'Reflex Arc',
    description: 'Reflex pathway sequence and key terms.',
    types: ['mcq', 'reverse', 'fill'],
    blueprint_codes: ['1.B.7'],
    tags: ['reflex', 'afferent', 'efferent'],
    query: 'reflex arc receptor afferent efferent',
  },
  {
    id: 'neuro-proprioceptors',
    title: 'Spindles vs GTO',
    description: 'Proprioceptor function differences in simple terms.',
    types: ['mcq', 'reverse', 'fill'],
    blueprint_codes: ['2.C'],
    tags: ['proprioceptor', 'muscle-spindle', 'golgi-tendon-organ'],
    query: 'muscle spindle golgi tendon organ proprioception',
  },
  {
    id: 'neuro-motor-units',
    title: 'Motor Units and Force',
    description: 'Recruitment and rate-coding fundamentals.',
    types: ['mcq', 'reverse'],
    blueprint_codes: ['1.B.7'],
    tags: ['motor-unit', 'recruitment', 'rate-coding'],
    query: 'motor unit recruitment rate coding',
  },
  {
    id: 'neuro-nociception',
    title: 'Nociception Basics',
    description: 'A-delta and C-fiber overview without diagnosis framing.',
    types: ['mcq', 'reverse', 'fill'],
    blueprint_codes: ['1.C'],
    tags: ['nociception', 'pain-signaling'],
    query: 'nociception a-delta c fiber',
  },
  {
    id: 'endo-insulin-glucagon',
    title: 'Insulin vs Glucagon',
    description: 'Glucose regulation essentials.',
    types: ['mcq', 'reverse', 'fill'],
    blueprint_codes: ['1.B.3'],
    tags: ['insulin', 'glucagon', 'glucose'],
    query: 'insulin glucagon blood glucose',
  },
  {
    id: 'endo-thyroid-basics',
    title: 'Thyroid Basics',
    description: 'Thyroid hormones and metabolism overview.',
    types: ['mcq', 'reverse'],
    blueprint_codes: ['1.B.3'],
    tags: ['thyroid', 'metabolism'],
    query: 'thyroid tsh metabolism',
  },
  {
    id: 'endo-feedback-loops',
    title: 'Feedback Loops',
    description: 'Negative feedback as a core endocrine control model.',
    types: ['mcq', 'reverse', 'fill'],
    blueprint_codes: ['1.B.3'],
    tags: ['feedback-loop', 'homeostasis'],
    query: 'negative feedback loop endocrine',
  },
  {
    id: 'endo-adrenal-basics',
    title: 'Adrenal Basics',
    description: 'Cortex vs medulla and high-level hormone roles.',
    types: ['mcq', 'reverse'],
    blueprint_codes: ['1.B.3'],
    tags: ['adrenal', 'cortisol', 'aldosterone', 'epinephrine'],
    query: 'adrenal cortex medulla cortisol aldosterone epinephrine',
  },
  {
    id: 'endo-scope-cautions',
    title: 'Endocrine Scope-Safe Cautions',
    description: 'Session pacing, pressure, communication, and referral cues.',
    types: ['mcq', 'reverse', 'fill'],
    blueprint_codes: ['3.C', '3.E', '5.G.1', '5.G.4', '6.H', '6.I'],
    tags: ['scope', 'caution', 'referral'],
    query: 'scope refer dizziness confusion swelling diabetes thyroid',
  },
  {
    id: 'cardio-scope-cautions',
    title: 'Cardio/Blood Cautions',
    description: 'General caution framing for BP, edema, veins, and meds.',
    types: ['mcq', 'reverse', 'fill'],
    blueprint_codes: ['3.C', '3.E', '5.G.1', '5.G.4', '6.H', '6.I'],
    tags: ['blood-pressure', 'edema', 'varicose-veins', 'anticoagulant'],
    query: 'blood pressure edema varicose anticoagulant refer',
  },
];
